// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: assignee.sql

package model

import (
	"context"
)

const assign = `-- name: Assign :exec
insert into assignee(space_id, ticket_id, identity_id)
values($1, $2, $3)
on conflict do nothing
`

type AssignParams struct {
	SpaceID    int32
	TicketID   int32
	IdentityID int32
}

func (q *Queries) Assign(ctx context.Context, arg AssignParams) error {
	_, err := q.db.Exec(ctx, assign, arg.SpaceID, arg.TicketID, arg.IdentityID)
	return err
}
