// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package model

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Assignee struct {
	SpaceID    int32
	TicketID   int32
	IdentityID int32
}

type Identity struct {
	ID             int32
	Email          string
	PasswordHash   []byte
	Name           string
	CurrentSpaceID pgtype.Int4
}

type Space struct {
	ID   int32
	Name string
}

type Ticket struct {
	SpaceID int32
	ID      int32
	Subject string
	Body    string
}

type User struct {
	SpaceID    int32
	IdentityID int32
}
